In [1]:
import random as rnd
import numpy as np

#

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
for_choice = [2, 3, 4, 6, 12]
for i in range(5):
    new_shape = rnd.choice(for_choice)
    b = a.reshape(new_shape, int(a.shape[0] / new_shape))
    print(f"a{i + 1} = ")
    print(b)
    print()
    for_choice.remove(new_shape)

a1 = 
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

a2 = 
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

a3 = 
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

a4 = 
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

a5 = 
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]



#

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
for_choice = [2, 3, 4, 6, 12]
for i in range(3):
    new_shape = rnd.choice(for_choice)
    b = a.reshape(new_shape, -1)
    print(f"a{i + 1} = ")
    print(b)
    print()
    for_choice.remove(new_shape)
    
for i in range(2):
    new_shape = rnd.choice(for_choice)
    b = a.reshape(-1, new_shape)
    print(f"a{i + 4} = ")
    print(b)
    print()
    for_choice.remove(new_shape)

a1 = 
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

a2 = 
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

a3 = 
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

a4 = 
[[12 13 14 15 16 17 18 19 20 21 22 23]]

a5 = 
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]



#

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [5]:
b = a.reshape(12, -1)
b.ndim

2

Ответ: с точки зрения логики Numpy нельзя, потому что у такого массива две оси. С мат. точки зрения думаю разницы нет и один столбец можно назвать одномерным, хотя дьявол в деталях))

#

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [6]:
a = np.random.rand(3, 4)
a

array([[0.12434926, 0.05848316, 0.17135866, 0.51895001],
       [0.06415671, 0.85414474, 0.1773805 , 0.56068169],
       [0.97907192, 0.60920559, 0.95764613, 0.66030382]])

In [7]:
b = a.ravel()
b

array([0.12434926, 0.05848316, 0.17135866, 0.51895001, 0.06415671,
       0.85414474, 0.1773805 , 0.56068169, 0.97907192, 0.60920559,
       0.95764613, 0.66030382])

In [8]:
b.shape

(12,)

In [9]:
a.shape

(3, 4)

#

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [10]:
a = np.arange(20, 0, -2)

In [11]:
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [12]:
b = a.reshape(1, -1)

In [13]:
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [14]:
b.ndim

2

Ответ: Разница в количестве осей, хоть вывод у них почти одинаковый. Массив b только выводится как матрица с двойными скобками. Соответсвенно на массиве a работают методы array, но не работают методы матриц, с b наоборот

#

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [15]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [16]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
c = np.vstack((a, b))
c

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
c.size

10

#

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [19]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
a = a.reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
At = a.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [22]:
B = np.matmul(a, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [23]:
B.shape

(4, 4)

In [24]:
B_inv = np.linalg.inv(B)

LinAlgError: Singular matrix

Ответ: нампай кидает ошибку про вырожденную матрицу, поскольку я не вижу линейно зависимых строк или столбцов, то можно сделать вывод, что определитель у нее нулевой

In [25]:
determinant_B = np.linalg.det(B)
determinant_B

0.0

#

 Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [26]:
np.random.seed(42)

In [27]:
a = np.random.rand(4)
a

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [28]:
a = np.random.rand(4)
a

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [29]:
a = np.random.rand(4)
a

array([0.60111501, 0.70807258, 0.02058449, 0.96990985])

#

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [30]:
c = np.random.randint(0, 16, (16))
c

array([11, 13,  5,  1, 15, 11,  4,  0, 11,  9,  5, 12, 11,  8,  0, 10])

#

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [31]:
C = c.reshape(4,4)
C

array([[11, 13,  5,  1],
       [15, 11,  4,  0],
       [11,  9,  5, 12],
       [11,  8,  0, 10]])

In [32]:
D = B + C.dot(10)
D

array([[115, 144,  73,  42],
       [164, 160, 126, 122],
       [133, 176, 199, 332],
       [142, 202, 212, 402]])

In [33]:
determinant_D = np.linalg.det(D)
determinant_D

-31734200.000000056

In [34]:
rank_D = np.linalg.matrix_rank(D)
rank_D

4

In [35]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.02273446,  0.03132204, -0.03241865,  0.01964316],
       [ 0.02434471, -0.02021478,  0.00035671,  0.00329676],
       [ 0.00561098, -0.0128423 ,  0.06299513, -0.04871464],
       [-0.00716136,  0.00586623, -0.02194919,  0.01958266]])

#

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [36]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[0., 1., 0., 1.],
       [1., 0., 1., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [38]:
E = np.where(D_inv == 1, B, C)
E

array([[ 11,  14,   5,  32],
       [ 14,  11,  86, 122],
       [ 23,   9, 149,  12],
       [ 11, 122,   0, 302]])